Traceback (most recent call last):
  File "/home/larbs/projects/desct/main.py", line 75, in <module>
    main()
  File "/home/larbs/projects/desct/main.py", line 44, in main
    model = load_model(
            ^^^^^^^^^^^
  File "/home/larbs/projects/desct/models/__init__.py", line 30, in load_model
    return model(config)
           ^^^^^^^^^^^^^
  File "/home/larbs/projects/desct/models/ect_model.py", line 61, in __init__
    self.ectlayer = GEctLayer(config)
                   ^^^^^^^^^^^^^^^^^
  File "/home/larbs/projects/desct/models/layers/layers.py", line 26, in __init__
    self.v = self.v.to(self.device)
    ^^^^^^
  File "/home/larbs/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1674, in __setattr__
    super().__setattr__(name, value)
  File "/home/larbs/.local/lib/python3.11/site-packages/geotorch/parametrize.py", line 360, in set_original
    self.parametrizations[tensor_name].right_inverse(value)
  File "/home/larbs/.local/lib/python3.11/site-packages/geotorch/parametrize.py", line 242, in right_inverse
    self.original.set_(value)  # type: ignore[call-overload]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Attempted to set the storage of a tensor on device "cpu" to a storage on different device "cuda:0".  This is no longer allowed; the devices must match.